### ISSUE TITLE
当概念类型instance有多个时，与概念类型之间的谓词关系，使用dsl无法查询

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#125]
在supplychain例子中，TaxOfCompanyEvent: ConceptType有两个instance，`TaxOfCompanyEvent`/`成本上涨`和`TaxOfCompanyEvent`/`利润下跌`。
根据如下定义：
```
`TaxOfCompanyEvent`/`成本上涨`:
    rule: [[
        Define (e:CompanyEvent)-[p:belongTo]->(o:`TaxOfCompanyEvent`/`成本上涨`) {
            Structure {
            }
            Constraint {
                R1: e.index == '成本'
                R2: e.trend == '上涨'
            }
        }
    ]]
```
如果创建了一个CompanyEvent( index == '成本'，trend == '上涨' 类型)，则会存在(e:CompanyEvent)-[p:belongTo]->(o:`TaxOfCompanyEvent`/`成本上涨`)这样一条边。
在tugraph中，能够直接查询出来这条边：
![image](https://github.com/OpenSPG/openspg/assets/52943316/b3dce0ac-5067-409c-bf4f-3d5e6b005b87)
但是在spg中使用如下dsl进行查询时，
```
knext reasoner execute --dsl "
MATCH
    (o:SupplyChain.CompanyEvent)-[e:belongTo]->(c:SupplyChain.TaxOfCompanyEvent)
WHERE o.subject='CSF0000000002'
RETURN                                             
    o.id,o.subject,o.name,o.belongTo,o.leadTo,o.index,o.trend                                 
"
```

会报如下错误：

```
java.lang.RuntimeException: com.antgroup.tugraph.TuGraphDbRpcException: CypherException: ParserException: line 1:38 no viable alternative at input 'MATCH (s:SupplyChain_TaxOfCompanyEvent/'
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.queryRecord(TuGraphStoreClient.java:111)
        at com.antgroup.openspg.reasoner.warehouse.cloudext.CloudExtGraphState.getVertexIterator(CloudExtGraphState.java:117)
        at com.antgroup.openspg.reasoner.runner.local.impl.LocalPropertyGraph.getStartIdList(LocalPropertyGraph.java:124)
        at com.antgroup.openspg.reasoner.runner.local.impl.LocalPropertyGraph.createRDG(LocalPropertyGraph.java:68)
        at com.antgroup.openspg.reasoner.runner.local.impl.LocalPropertyGraph.createRDG(LocalPropertyGraph.java:39)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Start.rdg(Start.scala:28)
        at com.antgroup.openspg.reasoner.lube.physical.operators.PatternScan.rdg(PatterScan.scala:27)
        at com.antgroup.openspg.reasoner.lube.physical.operators.ExpandInto.rdg(ExpandInto.scala:30)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Drop.rdg(Drop.scala:24)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Aggregate.rdg(Aggregate.scala:30)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Drop.rdg(Drop.scala:24)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Select.row(Select.scala:26)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:160)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:57)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.doMain(LocalReasonerMain.java:62)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.main(LocalReasonerMain.java:52)
Caused by: com.antgroup.tugraph.TuGraphDbRpcException: CypherException: ParserException: line 1:38 no viable alternative at input 'MATCH (s:SupplyChain_TaxOfCompanyEvent/'
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.handleGraphQueryRequest(TuGraphDbRpcClient.java:437)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.handleCypherRequest(TuGraphDbRpcClient.java:444)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.callCypher(TuGraphDbRpcClient.java:645)
        at com.antgroup.tugraph.TuGraphDbRpcClient.callCypher(TuGraphDbRpcClient.java:86)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.queryRecord(TuGraphStoreClient.java:109)
        ... 15 common frames omitted
2024-02-20 12:08:54,887 [] [] [main] ERROR c.a.o.r.r.l.LocalReasonerMain - KGReasonerLocalRunner,error:com.antgroup.tugraph.TuGraphDbRpcException: CypherException: ParserException: line 1:38 no viable alternative at input 'MATCH (s:SupplyChain_TaxOfCompanyEvent/'
```
看报错是spg向tugraph请求的查询语句为(s:SupplyChain_CompanyEvent)-[e:SupplyChain_CompanyEvent__belongTo__SupplyChain_TaxOfCompanyEvent]->(o:SupplyChain_TaxOfCompanyEvent/成本上涨)
tugraph接收这样的语句时会报错。

请问是否是我的dsl语句有误，还是spg的bug？

**Comment by royzhao** [comment]
不好意思，目前还未支持直接到概念根节点的推理，正在开发中

**Comment by royzhao** [comment]
现在只能指定到具体的概念实例例如
knext reasoner execute --dsl "
MATCH
    (o:SupplyChain.CompanyEvent)-[e:belongTo]->(c:SupplyChain.`TaxOfCompanyEvent`/`成本上涨`)
WHERE o.subject='CSF0000000002'
RETURN                                             
    o.id,o.subject,o.name,o.belongTo,o.leadTo,o.index,o.trend                                 
"

**Comment by billc114** [comment]
> 现在只能指定到具体的概念实例例如 knext reasoner execute --dsl " MATCH (o:SupplyChain.CompanyEvent)-[e:belongTo]->(c:SupplyChain.`TaxOfCompanyEvent`/`成本上涨`) WHERE o.subject='CSF0000000002' RETURN o.id,o.subject,o.name,o.belongTo,o.leadTo,o.index,o.trend "

还请再帮忙看一下。这条语句的语法好像不对T T
![image](https://github.com/OpenSPG/openspg/assets/52943316/1d43dd1a-cb84-4583-870d-a8137b3778cc)

**Comment by royzhao** [comment]
> > 现在只能指定到具体的概念实例例如 knext reasoner execute --dsl " MATCH (o:SupplyChain.CompanyEvent)-[e:belongTo]->(c:SupplyChain.`TaxOfCompanyEvent`/`成本上涨`) WHERE o.subject='CSF0000000002' RETURN o.id,o.subject,o.name,o.belongTo,o.leadTo,o.index,o.trend "
> 
> 还请再帮忙看一下。这条语句的语法好像不对T T ![image](https://private-user-images.githubusercontent.com/52943316/306480057-1d43dd1a-cb84-4583-870d-a8137b3778cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODU1NzAsIm5iZiI6MTcwODQ4NTI3MCwicGF0aCI6Ii81Mjk0MzMxNi8zMDY0ODAwNTctMWQ0M2RkMWEtY2I4NC00NTgzLTg3MGQtYTgxMzdiMzc3OGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzMTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NDFkZDRmNzk1ODZmNzExZWU4MmM2M2FhNDc3MTBhZWU1ZTU5NGJhYThjOTE3YzRhNTVlNDI3N2ZkYjNiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.roR7Cuj4AQwM3xCoeeCEkL9rLQ3tM9YpZUvM9hVELTc)

`knext reasoner execute --dsl "
MATCH
(o:SupplyChain.CompanyEvent)-[e:belongTo]->(c:`SupplyChain.TaxOfCompanyEvent`/`成本上涨`)
WHERE o.subject='CSF0000000002'
RETURN
o.id,o.subject,o.name,o.belongTo,o.leadTo,o.index,o.trend`

**Comment by billc114** [comment]
了解了，感谢解答~
