### ISSUE TITLE
关于执行黑产案例的knext builder execute TaxOfRiskUser,TaxOfRiskApp时产生的错误

### ISSUE THREAD

**Issue by zhui6688** [OpenSPG/openspg#127]
提交下面代码时
knext builder execute TaxOfRiskUser,TaxOfRiskApp
会有如下错误：
2024-02-22 04:59:16,497 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@55b0dcab
2024-02-22 04:59:16,511 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-02-22 04:59:16,512 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-02-22 04:59:18,445 [] [] [main] INFO  c.a.o.c.i.s.SearchEngineClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.searchengine.elasticsearch.ElasticSearchEngineClientDriver@5a411614
2024-02-22 04:59:18,450 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.searchengine.drivers = null
2024-02-22 04:59:18,452 [] [] [main] INFO  c.a.o.c.i.s.SearchEngineClientDriverManager - search-engine DriverManager initialized
2024-02-22 04:59:19,485 [] [] [main] INFO  c.a.o.b.r.l.r.BuilderMetric - type=COUNTER, name=default_job_error, count=0
2024-02-22 04:59:19,498 [] [] [main] INFO  c.a.o.b.r.l.r.BuilderMetric - type=METER, name=default_job_total, count=1, m1_rate=0.0, m5_rate=0.0, m15_rate=0.0, mean_rate=1.0264612797983494, rate_unit=events/second
2024-02-22 04:59:19,518 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: upsertIdxRecords error, errorMsg=
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.failFast(LocalBuilderRunner.java:149)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.execute(LocalBuilderRunner.java:124)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:151)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
Caused by: java.lang.RuntimeException: upsertIdxRecords error, errorMsg=
	at com.antgroup.openspg.cloudext.impl.searchengine.elasticsearch.util.ElasticSearchRecordUtils.upsertIdxRecords(ElasticSearchRecordUtils.java:65)
	at com.antgroup.openspg.cloudext.impl.searchengine.elasticsearch.ElasticSearchEngineClient.manipulateRecord(ElasticSearchEngineClient.java:105)
	at com.antgroup.openspg.cloudext.interfaces.searchengine.BaseIdxSearchEngineClient.manipulateRecord(BaseIdxSearchEngineClient.java:47)
	at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.batchWriteToSearchEngine(GraphStoreSinkWriter.java:93)
	at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.write(GraphStoreSinkWriter.java:75)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.lambda$execute$0(LocalBuilderRunner.java:112)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

代码打开时会有下图的报错，是找不到模块产生的。会是这个造成的吗？
![image](https://github.com/OpenSPG/openspg/assets/38718591/12afa42e-753b-4814-bbcd-27b860a548d9)

但是，我改成下图：
![image](https://github.com/OpenSPG/openspg/assets/38718591/89d7e37f-22f4-43c3-aa87-4b3ca87c1783)
又会有下面的报错：
Traceback (most recent call last):
  File "/openspg_venv/bin/knext", line 5, in <module>
    from knext.command.knext_cli import _main
  File "/openspg_venv/lib/python3.8/site-packages/knext/__init__.py", line 18, in <module>
    init_env()
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 61, in init_env
    load_builder_job()
  File "/openspg_venv/lib/python3.8/site-packages/knext/common/env.py", line 155, in load_builder_job
    register_from_package(builder_operator_path, BuilderJob)

请问为什么？我应该如何处理？

**Comment by zhui6688** [comment]
目前解决方案只能是全部重新下载，重新创建Docker容器。目前没再复现。该问题可能与我的另一个问题有关联性："关于使用riskmining运行时的错误"。但具体什么问题无法知道。
