### ISSUE TITLE
com.antgroup.tugraph.TuGraphDbRpcException: pair unique and unique configuration cannot occur simultaneously

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#129]
执行knext schema commit时报如下错误，请问是什么原因？
```
Caused by: java.lang.RuntimeException: com.antgroup.tugraph.TuGraphDbRpcException: pair_unique and unique configuration cannot occur simultaneously)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.createEdgeType(TuGraphStoreClient.java:228)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.BaseLPGGraphStoreClient.lambda$alterLPGSchemaOneByOne$7(BaseLPGGraphStoreClient.java:138)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.BaseLPGGraphStoreClient.alterLPGSchemaOneByOne(BaseLPGGraphStoreClient.java:138)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.BaseLPGGraphStoreClient.alterSchema(BaseLPGGraphStoreClient.java:95)
        at com.antgroup.openspg.server.core.schema.service.alter.sync.GraphStorageSyncer.syncSchema(GraphStorageSyncer.java:32)
        at com.antgroup.openspg.server.core.schema.service.alter.stage.PostProcessStage.syncSchema(PostProcessStage.java:64)
        at com.antgroup.openspg.server.core.schema.service.alter.stage.PostProcessStage.execute(PostProcessStage.java:51)
        at com.antgroup.openspg.server.core.schema.service.alter.SchemaAlterPipeline.run(SchemaAlterPipeline.java:40)
        at com.antgroup.openspg.server.biz.schema.impl.SchemaManagerImpl.alterSchema(SchemaManagerImpl.java:76)
        ... 73 common frames omitted
Caused by: com.antgroup.tugraph.TuGraphDbRpcException: pair_unique and unique configuration cannot occur simultaneously)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.handleGraphQueryRequest(TuGraphDbRpcClient.java:437)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.handleCypherRequest(TuGraphDbRpcClient.java:444)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.callCypher(TuGraphDbRpcClient.java:645)
        at com.antgroup.tugraph.TuGraphDbRpcClient.callCypher(TuGraphDbRpcClient.java:86)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.util.TuGraphSchemaUtils.addEdgeIndexes(TuGraphSchemaUtils.java:105)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.createEdgeType(TuGraphStoreClient.java:220)
        ... 90 common frames omitted

```

**Comment by billc114** [comment]
knext端收到的是
```
Traceback (most recent call last):
  File "/openspg_venv/bin/knext", line 8, in <module>
    sys.exit(_main())
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/openspg_venv/lib/python3.8/site-packages/knext/command/exception.py", line 29, in invoke
    return super().invoke(ctx)
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/openspg_venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/openspg_venv/lib/python3.8/site-packages/knext/command/sub_command/schema.py", line 60, in commit_schema
    is_altered = ml.sync_schema()
  File "/openspg_venv/lib/python3.8/site-packages/knext/client/marklang/schema_ml.py", line 946, in sync_schema
    return self.diff_and_sync(False)
  File "/openspg_venv/lib/python3.8/site-packages/knext/client/marklang/schema_ml.py", line 1249, in diff_and_sync
    session.commit()
  File "/openspg_venv/lib/python3.8/site-packages/knext/client/schema.py", line 152, in commit
    self._rest_client.schema_alter_schema_post(schema_alter_request=request)
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api/schema_api.py", line 69, in schema_alter_schema_post
    return self.schema_alter_schema_post_with_http_info(**kwargs)  # noqa: E501
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api/schema_api.py", line 145, in schema_alter_schema_post_with_http_info
    return self.api_client.call_api(
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api_client.py", line 418, in call_api
    return self.__call_api(
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api_client.py", line 220, in __call_api
    raise e
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api_client.py", line 208, in __call_api
    response_data = self.request(
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/api_client.py", line 494, in request
    return self.rest_client.POST(
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/rest.py", line 345, in POST
    return self.request(
  File "/openspg_venv/lib/python3.8/site-packages/knext/rest/rest.py", line 257, in request
    raise ApiException(http_resp=r)
knext.rest.exceptions.ApiException: (500)
Reason: 
HTTP response headers: HTTPHeaderDict({'Remote': '192.168.112.5', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Fri, 23 Feb 2024 07:09:27 GMT', 'Connection': 'close'})
HTTP response body: "com.antgroup.tugraph.TuGraphDbRpcException: pair_unique and unique configuration cannot occur simultaneously)"
```

**Comment by billc114** [comment]
使用for循环多次提交`for i in {1..50}; do   echo "这是第 $i 次循环";   knext schema commit; done`，在多轮报错后，能够提交成功
![image](https://github.com/OpenSPG/openspg/assets/52943316/ddef20a5-0414-4b9f-89a8-b7c4625be68b)
该问题在tugraph中已经导入大约134顶点 140条边。tugraph版本已升级到4.1.0

**Comment by J4ckycjl** [comment]
原因是相较于4.0.1版本，4.1.0版本的tugraph镜像在底层接口上有所改动，需要进行兼容。
您可以尝试先沿用4.0.1版本的tugraph镜像，目前，4.1.0版本的tugraph镜像已在适配中。
