### ISSUE TITLE
在docker环境中，执行 knext builder execute 报错  c.a.o.b.r.l.LocalBuilderMain - unknown exception. java.lang.NumberFormatException: For input string: "null

### ISSUE THREAD

**Issue by xiaoshan0609** [OpenSPG/openspg#138]
报错详情：
2024-03-05 06:23:57,750 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@131ef10
2024-03-05 06:23:57,752 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-03-05 06:23:57,752 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-03-05 06:23:57,766 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.lang.NumberFormatException: For input string: "null"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:82)
	at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
	at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
	at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
	at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
	at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
	at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:148)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)

docker-compose.yml文件：

server:
    restart: always
    image: openspg/openspg-server:latest
    container_name: release-openspg-server
    ports:
      - "12000:8887"
    depends_on:
      - mysql
      - tugraph
      - elasticsearch
    command: [
      '--server.repository.impl.jdbc.host=mysql',
      '--server.repository.impl.jdbc.password=openspg',
      '--cloudext.graphstore.url=tugraph://tugraph:9090?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph',
      '--cloudext.searchengine.url=elasticsearch://elasticsearch:9200?scheme=http'
    ]

tugraph:
    image: tugraph/tugraph-runtime-centos7:4.0.1
    container_name: release-openspg-tugraph
    # default username is admin and default password is 73@TuGraph
    ports:
      - "12002:7070"
      - "12003:9090"
    command: lgraph_server

已经参考issue#106 设置
knext config set --global graph_store_url="tugraph://127.0.01:12003？graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph"
还是报这个错误

**Comment by xiaoshan0609** [comment]
感觉是开启docker时换了端口，然后哪里没设置好，报的错，看报错像网络连接的问题

**Comment by xiaoshan0609** [comment]
好吧大哥们我解决了，要设置一下参数，另外，?一定是英文的

knext config set --global graph_store_url="tugraph://127.0.0.1:12003?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph"

knext config set --global search_engine_url="elasticsearch://127.0.0.1:12004?scheme=http"

**Comment by baifuyu** [comment]
> 好吧大哥们我解决了，要设置一下参数，另外，?一定是英文的
> 
> knext config set --global graph_store_url="tugraph://127.0.0.1:12003?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph"
> 
> knext config set --global search_engine_url="elasticsearch://127.0.0.1:12004?scheme=http"

是的。如果改了端口需要告知下knext，即配置下地址
