### ISSUE TITLE
请问rule_value中的判断条件是不是不支持float类型的参数？

### ISSUE THREAD

**Issue by billc114** [OpenSPG/openspg#171]
官方文档：
> rule_value
● 范式：rule_value (rule_name, true_value, false_value)
● 作用：将规则真值转换为指定值，如果rule_name的规则运算结果为true，则返回true_value,如果为false，则返回falsevalue

```
Fault实体): EntityType
	properties:
		vid(vid): Text
		baselevel(baselevel): Float
		threslevel(threslevel): Float
		bias(bias): Float
			rule: [[
				Define (s:Fault)-[p:bias]->(o:Float) {
					STRUCTURE {
						...
					}
					CONSTRAINT {
						num=(s.expression-s.baselevel)/(s.threslevel-s.baselevel)-0.5
						o=rule_value(s.baselevel<0,num,0)
					}
				}
			]]
```

在rule_value中的条件我使用了`s.baselevel<0`，报错如下：
```
com.ql.util.express.exception.QLBizException: run QlExpress Exception at line -1 :
        at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:38)
        at com.ql.util.express.InstructionSet.executeInnerOriginalInstruction(InstructionSet.java:196)
        at com.ql.util.express.InstructionSet.execute(InstructionSet.java:163)
        at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:59)
        at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:50)
        at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:22)
        at com.ql.util.express.ExpressRunner.executeReentrant(ExpressRunner.java:654)
        at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:641)
        at com.antgroup.openspg.reasoner.udf.rule.RuleRunner.executeExpression(RuleRunner.java:113)
        at com.antgroup.openspg.reasoner.rdg.common.KgGraphAddFieldsImpl.map(KgGraphAddFieldsImpl.java:113)
        at com.antgroup.openspg.reasoner.runner.local.rdg.LocalRDG.addFields(LocalRDG.java:778)
        at com.antgroup.openspg.reasoner.runner.local.rdg.LocalRDG.addFields(LocalRDG.java:111)
        at com.antgroup.openspg.reasoner.lube.physical.operators.AddInto.rdg(AddInto.scala:25)
        at com.antgroup.openspg.reasoner.lube.physical.operators.AddInto.rdg(AddInto.scala:25)
        at com.antgroup.openspg.reasoner.lube.physical.operators.Drop.rdg(Drop.scala:24)
        at com.antgroup.openspg.reasoner.lube.physical.operators.DDL.rdg(DDL.scala:48)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:172)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:66)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.doMain(LocalReasonerMain.java:62)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.main(LocalReasonerMain.java:52)
Caused by: java.lang.RuntimeException: unsupported type java.math.BigDecimal
        at com.antgroup.openspg.reasoner.common.Utils.javaType2KgType(Utils.java:129)
        at com.antgroup.openspg.reasoner.udf.model.RuntimeUdfMeta.getParamTypeList(RuntimeUdfMeta.java:133)
        at com.antgroup.openspg.reasoner.udf.model.RuntimeUdfMeta.invoke(RuntimeUdfMeta.java:95)
        at com.antgroup.openspg.reasoner.udf.rule.udf.UdfWrapper.executeInner(UdfWrapper.java:34)
        at com.ql.util.express.Operator.executeInner(Operator.java:26)
        at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:56)
        at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:32)
        ... 19 common frames omitted
```

**Comment by billc114** [comment]
我在修改了`com.antgroup.openspg.reasoner.udf.rule.udf.UdfWrapper#executeInne`r的代码之后运行成功了
对入参进行了如下转换：
```
    Object[] newObjs = Arrays.stream(objects).map(it -> {
      if (it.getClass().getName().equals("java.math.BigDecimal")) {
        BigDecimal bd = new BigDecimal(it.toString());
        Double aDouble = new Double(bd.doubleValue());
        Object object = aDouble;
        return object;
      } else {
        return it;
      }
    }).collect(Collectors.toList()).toArray(new Object[0]);
```

**Comment by youdonghai** [comment]
主要原因是udf对BigDecimal类型还不支持。这个问题我们会跟进修复。
