### ISSUE TITLE
企业供应链案例里面，产业链影响的事件查询结果为空，原因应该是构建事件时报错

### ISSUE THREAD

**Issue by zwx1185** [OpenSPG/openspg#22]
亲爱的OpenSPG开发团队，您好~
  我在尝试运行产业链示例时，发现其中场景三：产业链影响，在构建商品产业链事件时会报错，导致无法构建，从而在利用给出的GQL查询产业链影响时，得到的结果为空。
  所参考的教程地址：https://spg.openkg.cn/example/enterprise-supply-chain/query#%E5%9C%BA%E6%99%AF3%E4%BA%A7%E4%B8%9A%E9%93%BE%E5%BD%B1%E5%93%8D
  场景为场景3：产业链影响

具体：
在执行 knext builder submit ProductChainEvent 构建产品供应链事件时，客户端报错：
023-12-10 07:48:54,566 [] [] [localBuilderExecutor-2] WARN  c.a.o.c.s.e.r.i.DefaultPipelineExecutor - process record(id=line2) error
2023-12-10 15:48:54 release-openspg             | com.antgroup.openspg.core.spgbuilder.engine.runtime.BuilderRecordException: spgType=SupplyChain.TaxOfProdEvent, value=价格上涨 concept mount failed
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.fireDag(DefaultPipelineExecutor.java:123)
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.execute(DefaultPipelineExecutor.java:90)
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.cloudext.impl.computing.local.impl.LocalBuilderExecutorImpl.lambda$doSubmit$0(LocalBuilderExecutorImpl.java:153)
2023-12-10 15:48:54 release-openspg             |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2023-12-10 15:48:54 release-openspg             |       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-12-10 15:48:54 release-openspg             |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-12-10 15:48:54 release-openspg             |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-12-10 15:48:54 release-openspg             |       at java.lang.Thread.run(Thread.java:750)
2023-12-10 15:48:54 release-openspg             | Caused by: com.antgroup.openspg.core.spgbuilder.engine.runtime.BuilderRecordException: spgType=SupplyChain.TaxOfProdEvent, value=价格上涨 concept mount failed
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.mount(MappingProcessor.java:267)
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.propertyMount(MappingProcessor.java:249)
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.process(MappingProcessor.java:137)
2023-12-10 15:48:54 release-openspg             |       at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.fireDag(DefaultPipelineExecutor.java:121)
2023-12-10 15:48:54 release-openspg             |       ... 7 common frames omitted

导致构建失败，从而，在使用命令： 
MATCH
    (s:SupplyChain.ProductChainEvent)-[:leadTo]->(o:SupplyChain.CompanyEvent)
RETURN
    s.id,s.subject,o.subject,o.name

查询产业链影响时，得到结果为空：
(openspg) foxyrep@foxyrepdeMacBook-Pro supplychain % knext reasoner query --dsl "
MATCH
    (s:SupplyChain.ProductChainEvent)-[:leadTo]->(o:SupplyChain.CompanyEvent)
RETURN
    s.id,s.subject,o.subject,o.name
"
| s_id   | s_subject   | o_subject   | o_name   |
|--------|-------------|-------------|----------|
(openspg) foxyrep@foxyrepdeMacBook-Pro supplychain %

**Comment by baifuyu** [comment]
> 亲爱的OpenSPG开发团队，您好~ 我在尝试运行产业链示例时，发现其中场景三：产业链影响，在构建商品产业链事件时会报错，导致无法构建，从而在利用给出的GQL查询产业链影响时，得到的结果为空。 所参考的教程地址：https://spg.openkg.cn/example/enterprise-supply-chain/query#%E5%9C%BA%E6%99%AF3%E4%BA%A7%E4%B8%9A%E9%93%BE%E5%BD%B1%E5%93%8D 场景为场景3：产业链影响
> 
> 具体： 在执行 knext builder submit ProductChainEvent 构建产品供应链事件时，客户端报错： 023-12-10 07:48:54,566 [] [] [localBuilderExecutor-2] WARN c.a.o.c.s.e.r.i.DefaultPipelineExecutor - process record(id=line2) error 2023-12-10 15:48:54 release-openspg | com.antgroup.openspg.core.spgbuilder.engine.runtime.BuilderRecordException: spgType=SupplyChain.TaxOfProdEvent, value=价格上涨 concept mount failed 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.fireDag(DefaultPipelineExecutor.java:123) 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.execute(DefaultPipelineExecutor.java:90) 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.cloudext.impl.computing.local.impl.LocalBuilderExecutorImpl.lambda$doSubmit$0(LocalBuilderExecutorImpl.java:153) 2023-12-10 15:48:54 release-openspg | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 2023-12-10 15:48:54 release-openspg | at java.util.concurrent.FutureTask.run(FutureTask.java:266) 2023-12-10 15:48:54 release-openspg | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 2023-12-10 15:48:54 release-openspg | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 2023-12-10 15:48:54 release-openspg | at java.lang.Thread.run(Thread.java:750) 2023-12-10 15:48:54 release-openspg | Caused by: com.antgroup.openspg.core.spgbuilder.engine.runtime.BuilderRecordException: spgType=SupplyChain.TaxOfProdEvent, value=价格上涨 concept mount failed 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.mount(MappingProcessor.java:267) 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.propertyMount(MappingProcessor.java:249) 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.physical.process.MappingProcessor.process(MappingProcessor.java:137) 2023-12-10 15:48:54 release-openspg | at com.antgroup.openspg.core.spgbuilder.engine.runtime.impl.DefaultPipelineExecutor.fireDag(DefaultPipelineExecutor.java:121) 2023-12-10 15:48:54 release-openspg | ... 7 common frames omitted
> 
> 导致构建失败，从而，在使用命令： MATCH (s:SupplyChain.ProductChainEvent)-[:leadTo]->(o:SupplyChain.CompanyEvent) RETURN s.id,s.subject,o.subject,o.name
> 
> 查询产业链影响时，得到结果为空： (openspg) foxyrep@foxyrepdeMacBook-Pro supplychain % knext reasoner query --dsl " MATCH (s:SupplyChain.ProductChainEvent)-[:leadTo]->(o:SupplyChain.CompanyEvent) RETURN s.id,s.subject,o.subject,o.name "
> 
> s_id	s_subject	o_subject	o_name
> (openspg) foxyrep@foxyrepdeMacBook-Pro supplychain %

十分抱歉给您造成了使用上不好的体验。

需要您这边确认下知识构建时是否使用命令knext builder submit TaxOfCompanyEvent,TaxOfProdEvent，导入过公司事件分类和产品事件分类的数据，如果没有导入会导致概念挂载失败；

**Comment by zwx1185** [comment]
亲爱的OpenSPG开发团队，您好！
非常感谢您的快速回复！（即使是在周日傍晚T_T）
您的提示是正确的，我没有注意到 知识建模 步骤中公司事件分类数据和产品事件分类数据的提交。在提交之后，再次查询产业链影响，得到了正确的结果！谢谢帮助！
OpenSPG是非常有意义的项目，感谢您的团队的付出，期待之后可以就项目与您有更多交流机会！

**Comment by baifuyu** [comment]
> 亲爱的OpenSPG开发团队，您好！ 非常感谢您的快速回复！（即使是在周日傍晚T_T） 您的提示是正确的，我没有注意到 知识建模 步骤中公司事件分类数据和产品事件分类数据的提交。在提交之后，再次查询产业链影响，得到了正确的结果！谢谢帮助！ OpenSPG是非常有意义的项目，感谢您的团队的付出，期待之后可以就项目与您有更多交流机会！

非常感谢您对 OpenSPG 的关注和问题反馈，OpenSPG刚刚开源不久，我们也在持续完善文档和功能。也欢迎您提供更具体的反馈，我们可以更快更准确地解决您的问题，也欢迎您参与到项目的社区共建中来。

构建企业级的语义框架和知识引擎，持续降低领域图谱的落地门槛和迁移成本是OpenSPG持续坚持的方向。近期我们也将发布构建原则和最佳实践，以减少用户理解成本。

20240101左右我们会升级下系统架构，当前的架构还有点不太合理，比如您这里的错误日志现在是比较难找的。欢迎关注OpenSPG的发布动态， 我们将第一时间通知，再次表达感谢！
