### ISSUE TITLE
本地执行 knext builder execute BodyPart 报错

### ISSUE THREAD

**Issue by lizhongxiang12138** [OpenSPG/openspg#234]
系统 macos
代码分支 master
安装了 pip install openspg-knext
cd python/knext/knext//examples/medicine
执行 knext builder execute BodyPart
报错：Error: Unable to access jarfile /Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/venv/lib/python3.10/site-packages/knext/builder/lib/builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar
后面手动把 docker 客户端的 jar 包复制到该目录下，再次执行 knext builder execute BodyPart
报错：
2024-05-07 10:20:58,129 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@65e98b1c
2024-05-07 10:20:58,132 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-05-07 10:20:58,132 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-05-07 10:20:58,817 [] [] [main] ERROR c.b.b.c.BrpcProxy - exception :
com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:268)
        at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
        at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
        at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
        at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
        at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.RpcFuture.get(RpcFuture.java:178)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:93)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
        at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
        at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
        at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
        at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
        at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
        ... 14 common frames omitted
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.handler.RpcClientHandler$2.run(RpcClientHandler.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.handler.RpcClientHandler.channelRead0(RpcClientHandler.java:68)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 common frames omitted
Caused by: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decode(BaiduRpcProtocol.java:190)
        at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decode(BaiduRpcProtocol.java:70)
        at com.baidu.brpc.client.handler.RpcClientHandler.channelRead0(RpcClientHandler.java:56)
        ... 17 common frames omitted
2024-05-07 10:20:58,823 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.lang.RuntimeException: init TuGraph Client failed
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
        at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
        at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
        at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
        at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:277)
        at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
        at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
        at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
        at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
        ... 10 common frames omitted
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.RpcFuture.get(RpcFuture.java:178)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:93)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
        at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
        at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
        at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
        at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
        at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
        at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
        ... 14 common frames omitted
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.handler.RpcClientHandler$2.run(RpcClientHandler.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.client.handler.RpcClientHandler.channelRead0(RpcClientHandler.java:68)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 common frames omitted
Caused by: com.baidu.brpc.exceptions.BadSchemaException: not valid magic head for brpc
        at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decode(BaiduRpcProtocol.java:190)
        at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decode(BaiduRpcProtocol.java:70)
        at com.baidu.brpc.client.handler.RpcClientHandler.channelRead0(RpcClientHandler.java:56)
        ... 17 common frames omitted

**Comment by andylau-55** [comment]
请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。

**Comment by lizhongxiang12138** [comment]
> 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。

使用 docker 的客户端可以执行成功

**Comment by lizhongxiang12138** [comment]
> 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。

['java', '-jar', '/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/builder/lib/builder-runner-local-0.0.1-SNAPSHOT-jar-with-dependencies.jar', '--projectId', '5', '--jobName', 'default_job', '--pipeline', '{"nodes": [{"id": "140408061158128", "name": "CSVReader", "nodeConfig": {"type": "CSV_SOURCE", "startRow": 1, "url": "/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/examples/medicine/builder/job/data/BodyPart.csv", "columns": ["id"], "@type": "CSV_SOURCE"}}, {"id": "140408064575664", "name": "_SPGTypeMappings", "nodeConfig": {"type": "SPG_TYPE_MAPPINGS", "mappingNodeConfigs": [{"type": "SPG_TYPE_MAPPING", "spgType": "Medicine.BodyPart", "mappingFilters": [], "mappingConfigs": [{"source": "id", "target": "id", "mappingType": "PROPERTY"}], "@type": "SPG_TYPE_MAPPING"}], "@type": "SPG_TYPE_MAPPINGS"}}, {"id": "140408064577184", "name": "KGWriter", "nodeConfig": {"type": "GRAPH_SINK", "@type": "GRAPH_SINK"}}], "edges": [{"from": "140408061158128", "to": "140408064575664"}, {"from": "140408064575664", "to": "140408064577184"}]}', '--pythonExec', '/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/venv/bin/python', '--pythonPaths', '/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/venv/bin;/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev;/Applications/PyCharm.app/Contents/plugins/python/helpers/third_party/thriftpy;/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext;/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_display;/Users/lizhongxiang/Library/Caches/JetBrains/PyCharm2022.3/cythonExtensions;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/examples/medicine;/Users/lizhongxiang/opt/anaconda3/envs/py10/lib/python310.zip;/Users/lizhongxiang/opt/anaconda3/envs/py10/lib/python3.10;/Users/lizhongxiang/opt/anaconda3/envs/py10/lib/python3.10/lib-dynload;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/venv/lib/python3.10/site-packages;/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm_matplotlib_backend;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/examples/medicine/builder/operator;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/builder/operator/builtin;/Users/lizhongxiang/PycharmProjects/pythonProject/openspg/python/knext/knext/examples/medicine/builder/job', '--schemaUrl', 'http://localhost:8887', '--parallelism', '1', '--alterOperation', <AlterOperationEnum.Upsert: 'UPSERT'>, '--logFile', '2024-05-07_14-26-45.log', '--graphStoreUrl', 'tugraph://127.0.0.1:9090?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph', '--searchEngineUrl', 'elasticsearch://127.0.0.1:9200?scheme=http']
执行 java 得命令

**Comment by andylau-55** [comment]
> > 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。
> 
> 使用 docker 的客户端可以运行成功，本地源码就不行

确认本地环境是否和docker中的TuGraph进行正常通信

**Comment by lizhongxiang12138** [comment]
> > > 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。
> > 
> > 
> > 使用 docker 的客户端可以运行成功，本地源码就不行
> 
> 确认本地环境是否和docker中的TuGraph进行正常通信

version: "3.7"
services:
  server:
    restart: always
    image: openspg/openspg-server:latest
    container_name: release-openspg-server
    ports:
      - "8887:8887"
    depends_on:
      - mysql
      - tugraph
      - elasticsearch
    command: [
      '--server.repository.impl.jdbc.host=mysql',
      '--server.repository.impl.jdbc.password=openspg',
      '--cloudext.graphstore.url=tugraph://tugraph:9090?graphName=default&timeout=50000&accessId=admin&accessKey=73@TuGraph',
      '--cloudext.searchengine.url=elasticsearch://elasticsearch:9200?scheme=http'
    ]

  mysql:
    restart: always
    image: openspg/openspg-mysql:latest
    container_name: release-openspg-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: openspg
      MYSQL_DATABASE: openspg
    ports:
      - "23306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci'
    ]

  tugraph:
    image: tugraph/tugraph-runtime-centos7:4.0.1
    container_name: release-openspg-tugraph
    environment:
      TZ: Asia/Shanghai
    # default username is admin and default password is 73@TuGraph
    ports:
      - "7070:7070"
      - "9090:9090"
    command: lgraph_server

  elasticsearch:
    image: elasticsearch:8.5.3
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

**Comment by lizhongxiang12138** [comment]
> > > 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。
> > 
> > 
> > 使用 docker 的客户端可以运行成功，本地源码就不行
> 
> 确认本地环境是否和docker中的TuGraph进行正常通信

<img width="1832" alt="image" src="https://github.com/OpenSPG/openspg/assets/20783890/90455e70-5a6a-4390-bb79-637a0d698960">

**Comment by lizhongxiang12138** [comment]
> > > > 请先检查schema是否创建成功，或尝试其他案例是否能正常执行，确保环境OK。报错信息提示与TuGraph通信失败，请勿修改TuGraph相关配置，并保证TuGraph正常启动，可根据异常日志提示进行解决。
> > > 
> > > 
> > > 使用 docker 的客户端可以运行成功，本地源码就不行
> > 
> > 
> > 确认本地环境是否和docker中的TuGraph进行正常通信
> 
> <img alt="image" width="1832" src="https://private-user-images.githubusercontent.com/20783890/328427924-90455e70-5a6a-4390-bb79-637a0d698960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjc1ODAsIm5iZiI6MTcxNTA2NzI4MCwicGF0aCI6Ii8yMDc4Mzg5MC8zMjg0Mjc5MjQtOTA0NTVlNzAtNWE2YS00MzkwLWJiNzktNjM3YTBkNjk4OTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZTU1NDgyYTc3NDgzZDMzZDdkODdjZDdlMDM1YmI2MDhiZTc0YjU2ZDUxMzQzZTVlYThjZTM3ZWRhMjY3ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTWD-NtLSe3H4AuXoH5ZhRlXazr_QFujehsyVdcImgA">

<img width="757" alt="image" src="https://github.com/OpenSPG/openspg/assets/20783890/78c4c555-c424-4935-9a5b-6cfcbd27ae21">

**Comment by lizhongxiang12138** [comment]
127.0.0.1:9090被其他程序占用，换了就可以了
