### ISSUE TITLE
医疗图谱中的step5：执行图谱任务在docker里面输入命令会出现错误如下，能帮忙解决下么？

### ISSUE THREAD

**Issue by bijinacm** [OpenSPG/openspg#286]
输入：knext reasoner execute --dsl "
MATCH
    (s:Medical.Disease)-[p]->(o)
RETURN
    s
"
错误：
2024-06-20 05:10:00,586 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@7995092a
2024-06-20 05:10:00,589 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-06-20 05:10:00,589 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-06-20 05:10:02,872 [] [] [main] INFO  lube - benchmark planToBlock cost = 823
2024-06-20 05:10:02,873 [] [] [main] INFO  lube - benchmark registerSchema cost = 1
2024-06-20 05:10:03,028 [] [] [main] INFO  lube - └─TableResultBlock(selectList=OrderedFields(List(IRProperty(s,__property_json__))), asList=List(s), distinct=false)
    └─MatchBlock(patterns=Map(unresolved_default_path -> GraphPath(unresolved_default_path,GraphPattern(null,Map(s -> (s:Medical.Disease), o -> (o:)),Map(s -> Set((s)->[p:]-(o)))),Map(s -> Set(__property_json__), p -> Set(), o -> Set())),false)))
        └─SourceBlock(graph=KG(Map(s -> IRNode(s,Set(__property_json__)), o -> IRNode(o,Set())),Map(p -> IREdge(p,Set()))))
2024-06-20 05:10:03,028 [] [] [main] INFO  lube - benchmark main plan plan2UnresolvedLogicalPlan cost = 979
2024-06-20 05:10:03,029 [] [] [main] INFO  lube - benchmark LogicalPlannerContext cost = 1
2024-06-20 05:10:03,047 [] [] [main] ERROR c.a.o.r.r.l.LocalReasonerRunner - KGReasonerLocalRunner,error
com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), p -> Set(), o -> Set())
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:126)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar(Validator.scala:126)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:112)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve$1.apply(Validator.scala:107)
        at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:179)
        at com.antgroup.openspg.reasoner.common.trees.Transform.transform(TreeTransformer.scala:174)
        at com.antgroup.openspg.reasoner.common.trees.AbstractTreeNode.transform(AbstractTreeNode.scala:60)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$resolve(Validator.scala:107)
        at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$.validate(Validator.scala:52)
        at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2LogicalPlan(KGReasonerSession.scala:325)
        at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan2OptimizedLogicalPlan(KGReasonerSession.scala:189)
        at com.antgroup.openspg.reasoner.session.KGReasonerSession.planBlock(KGReasonerSession.scala:172)
        at com.antgroup.openspg.reasoner.session.KGReasonerSession.plan(KGReasonerSession.scala:165)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.doRun(LocalReasonerRunner.java:104)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerRunner.run(LocalReasonerRunner.java:68)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.doMain(LocalReasonerMain.java:62)
        at com.antgroup.openspg.reasoner.runner.local.LocalReasonerMain.main(LocalReasonerMain.java:52)
2024-06-20 05:10:03,047 [] [] [main] ERROR c.a.o.r.r.l.LocalReasonerMain - KGReasonerLocalRunner,error:Cannot find s in Map(s -> Set(), p -> Set(), o -> Set())

**Comment by andylau-55** [comment]
抱歉，文档中Medicine输入有误，已经进行更新，请输入以下命令进行查询。
MATCH (s:Medicine.Disease)-[p]->(o)
RETURN s
感谢你的反馈

**Comment by bijinacm** [comment]
> 抱歉，文档中Medicine输入有误，已经进行更新，请输入以下命令进行查询。 MATCH (s:Medicine.Disease)-[p]->(o) RETURN s 感谢你的反馈

不是这个问题，你看这个位置
2024-06-20 05:10:03,047 [] [] [main] ERROR c.a.o.r.r.l.LocalReasonerRunner - KGReasonerLocalRunner,error
com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), p -> Set(), o -> Set())
at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130)

**Comment by andylau-55** [comment]
请问执行 MATCH (s:Medicine.Disease)-[p]->(o)
RETURN s  还是报错吗？我本地这样执行是完全ok的

**Comment by andylau-55** [comment]
> > 抱歉，文档中Medicine输入有误，已经进行更新，请输入以下命令进行查询。 MATCH (s:Medicine.Disease)-[p]->(o) RETURN s 感谢你的反馈
> 
> 不是这个问题，你看这个位置 2024-06-20 05:10:03,047 [] [] [main] ERROR c.a.o.r.r.l.LocalReasonerRunner - KGReasonerLocalRunner,error com.antgroup.openspg.reasoner.common.exception.SchemaException: Cannot find s in Map(s -> Set(), p -> Set(), o -> Set()) at com.antgroup.openspg.reasoner.lube.logical.validate.Validator$$anonfun$com$antgroup$openspg$reasoner$lube$logical$validate$Validator$$fieldToVar$1.apply(Validator.scala:130)

报错信息是 Cannot find s in Map  找不到s 。s:Medical.Disease是错误的，正确应该为s:Medicine.Disease
