### ISSUE TITLE
医疗图谱在执行”knext builder execute Disease“时报错

### ISSUE THREAD

**Issue by serendipitytoys** [OpenSPG/openspg#299]
之前运行成功过的，今天又试了一下，出现报错了，请问怎么解决？
![image](https://github.com/OpenSPG/openspg/assets/168266083/34c180be-9d52-42ac-83e8-40135b6fc3cf)

**Comment by andylau-55** [comment]
请提供下具体的日志信息，以及knext的版本信息等内容

**Comment by serendipitytoys** [comment]
knext版本：0.0.3-beta1
Logs：
2024-06-29 19:07:24 (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute BodyPart,HospitalDepartment
2024-06-29 19:07:26 2024-06-29 11:07:26,779 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@55b0dcab
2024-06-29 19:07:26 2024-06-29 11:07:26,784 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-06-29 19:07:26 2024-06-29 11:07:26,785 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-06-29 19:07:27 2024-06-29 11:07:27,361 [] [] [main] ERROR c.b.b.c.BrpcProxy - exception :
2024-06-29 19:07:27 com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:268)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
2024-06-29 19:07:27     at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
2024-06-29 19:07:27 Caused by: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27     at com.baidu.brpc.client.RpcClient.selectChannel(RpcClient.java:331)
2024-06-29 19:07:27     at com.baidu.brpc.client.RpcClient.sendRequest(RpcClient.java:389)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:88)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:27     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
2024-06-29 19:07:27     ... 14 common frames omitted
2024-06-29 19:07:27 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27 Caused by: java.net.ConnectException: Connection refused
2024-06-29 19:07:27     at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2024-06-29 19:07:27     at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
2024-06-29 19:07:27     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
2024-06-29 19:07:27     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2024-06-29 19:07:27     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2024-06-29 19:07:27     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-06-29 19:07:27     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-06-29 19:07:27     at java.lang.Thread.run(Thread.java:750)
2024-06-29 19:07:27 2024-06-29 11:07:27,362 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
2024-06-29 19:07:27 java.lang.RuntimeException: init TuGraph Client failed
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
2024-06-29 19:07:27     at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
2024-06-29 19:07:27     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
2024-06-29 19:07:27 Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:277)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
2024-06-29 19:07:27     at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
2024-06-29 19:07:27     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
2024-06-29 19:07:27     ... 10 common frames omitted
2024-06-29 19:07:27 Caused by: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27     at com.baidu.brpc.client.RpcClient.selectChannel(RpcClient.java:331)
2024-06-29 19:07:27     at com.baidu.brpc.client.RpcClient.sendRequest(RpcClient.java:389)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:88)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
2024-06-29 19:07:27     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:27     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
2024-06-29 19:07:27     ... 14 common frames omitted
2024-06-29 19:07:27 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9090
2024-06-29 19:07:27 Caused by: java.net.ConnectException: Connection refused
2024-06-29 19:07:27     at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2024-06-29 19:07:27     at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
2024-06-29 19:07:27     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
2024-06-29 19:07:27     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2024-06-29 19:07:27     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2024-06-29 19:07:27     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2024-06-29 19:07:27     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-06-29 19:07:27     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-06-29 19:07:27     at java.lang.Thread.run(Thread.java:750)
2024-06-29 19:07:28 2024-06-29 11:07:28,614 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - registerDriver: com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver@55b0dcab
2024-06-29 19:07:28 2024-06-29 11:07:28,618 [] [] [main] INFO  c.a.o.c.u.DriverManagerUtils - DriverManager.initialize: cloudext.graphstore.drivers = null
2024-06-29 19:07:28 2024-06-29 11:07:28,618 [] [] [main] INFO  c.a.o.c.i.g.GraphStoreClientDriverManager - graph-store DriverManager initialized
2024-06-29 19:07:29 2024-06-29 11:07:29,010 [] [] [main] ERROR c.b.b.c.BrpcProxy - exception :
2024-06-29 19:07:29 com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:268)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
2024-06-29 19:07:29     at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
2024-06-29 19:07:29 Caused by: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29     at com.baidu.brpc.client.RpcClient.selectChannel(RpcClient.java:331)
2024-06-29 19:07:29     at com.baidu.brpc.client.RpcClient.sendRequest(RpcClient.java:389)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:88)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:29     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
2024-06-29 19:07:29     ... 14 common frames omitted
2024-06-29 19:07:29 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29 Caused by: java.net.ConnectException: Connection refused
2024-06-29 19:07:29     at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2024-06-29 19:07:29     at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
2024-06-29 19:07:29     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
2024-06-29 19:07:29     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2024-06-29 19:07:29     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2024-06-29 19:07:29     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-06-29 19:07:29     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-06-29 19:07:29     at java.lang.Thread.run(Thread.java:750)
2024-06-29 19:07:29 2024-06-29 11:07:29,011 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
2024-06-29 19:07:29 java.lang.RuntimeException: init TuGraph Client failed
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:142)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.<init>(TuGraphStoreClient.java:84)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:36)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClientDriver.innerConnect(TuGraphStoreClientDriver.java:22)
2024-06-29 19:07:29     at com.antgroup.openspg.common.util.cloudext.CachedCloudExtClientDriver.connect(CachedCloudExtClientDriver.java:29)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.interfaces.graphstore.GraphStoreClientDriverManager.getClient(GraphStoreClientDriverManager.java:49)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.physical.sink.impl.GraphStoreSinkWriter.doInit(GraphStoreSinkWriter.java:59)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:76)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
2024-06-29 19:07:29     at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
2024-06-29 19:07:29 Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:277)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbService$$EnhancerByCGLIB$$3f8070da.HandleRequest(<generated>)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbRpcClient$TuGraphSingleRpcClient.<init>(TuGraphDbRpcClient.java:419)
2024-06-29 19:07:29     at com.antgroup.tugraph.TuGraphDbRpcClient.<init>(TuGraphDbRpcClient.java:63)
2024-06-29 19:07:29     at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:139)
2024-06-29 19:07:29     ... 10 common frames omitted
2024-06-29 19:07:29 Caused by: com.baidu.brpc.exceptions.RpcException: channel pool make new object failed, active=0,idle=0,server=127.0.0.1:9090, ex=Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29     at com.baidu.brpc.client.RpcClient.selectChannel(RpcClient.java:331)
2024-06-29 19:07:29     at com.baidu.brpc.client.RpcClient.sendRequest(RpcClient.java:389)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:88)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:82)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:62)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
2024-06-29 19:07:29     at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
2024-06-29 19:07:29     at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:266)
2024-06-29 19:07:29     ... 14 common frames omitted
2024-06-29 19:07:29 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9090
2024-06-29 19:07:29 Caused by: java.net.ConnectException: Connection refused
2024-06-29 19:07:29     at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2024-06-29 19:07:29     at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
2024-06-29 19:07:29     at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
2024-06-29 19:07:29     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
2024-06-29 19:07:29     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
2024-06-29 19:07:29     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2024-06-29 19:07:29     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-06-29 19:07:29     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-06-29 19:07:29     at java.lang.Thread.run(Thread.java:750)
2024-06-29 19:08:34 (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute Disease
2024-06-29 19:08:36 ERROR: cannot unpack non-iterable NoneType object
2024-06-29 19:24:20 (openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/medicine# knext builder execute Disease
2024-06-29 19:24:21 ERROR: cannot unpack non-iterable NoneType object
