### ISSUE TITLE
centos9中执行knext schema commit遇到ERROR: init TuGraph Client failed

### ISSUE THREAD

**Issue by evilbear** [OpenSPG/openspg#326]
系统环境centos9

**Comment by evilbear** [comment]
使用docker部署服务端

**Comment by evilbear** [comment]
使用docker部署服务端
使用源码启动和docker启动两种方式启动客户端获得一样的报错

**Comment by evilbear** [comment]
使用docker部署服务端，配置没有修改
使用源码启动和docker启动两种方式启动客户端获得一样的报错

执行到knext schema commit的时候遇到报错
使用tugraph/tugraph-runtime-centos7:4.0.1镜像的时候 部分报错信息如下：
Caused by: java.lang.RuntimeException: init TuGraph Client failed
Caused by: com.antgroup.tugraph.TuGraphDbRpcException: Timeout while compiling plugin.
at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:140)
定位到loadCppPlugin(client)这个操作tugraph报错

尝试切换为ubuntu的镜像tugraph/tugraph-runtime-ubuntu18.04:latest  部分报错信息如下：
Caused by: java.lang.RuntimeException: init TuGraph Client failed
Caused by: com.antgroup.tugraph.TuGraphDbRpcException: No permission to load or delete plugin, please use correct config and restart server! This function has security risks, please enable it with caution!
at com.antgroup.openspg.cloudext.impl.graphstore.tugraph.TuGraphStoreClient.initTuGraphClient(TuGraphStoreClient.java:140)
还是loadCppPlugin(client)这个位置

但是我在另一台ubuntu的主机上使用tugraph/tugraph-runtime-centos7:4.0.1的镜像一把过 没遇到报错

**Comment by andylau-55** [comment]
The error message you've encountered pertains to TuGraph, a distributed graph database developed by Ant Group. Specifically, it indicates that there's an issue with permissions related to loading or deleting a plugin within the TuGraph server environment.Please download tugraph from [docker-compose.yml](https://github.com/OpenSPG/openspg/blob/master/dev/release/docker-compose.yml) without making any configuration changes

**Comment by evilbear** [comment]
我第一步是没有修改docker-compose.yml中的任何内容，遇到超时的报错
第二步是尝试修改tugraph的镜像，遇到权限问题
然后在两台不同的centos9机器上遇到相同的问题

进一步的尝试发现是往tugraph里加载upsert_edges.cpp和upsert_vertices.cpp出问题
和这里的问题一样 https://github.com/OpenSPG/openspg/issues/307

尝试1: 使用7070端口登录tugraph的web界面，添加插件有报错
![image](https://github.com/user-attachments/assets/366f9180-cb28-46a8-a1e0-f49b1e5c4c50)
在tugraph的container中会创建一个tmp文件，但是不会存下来
![image](https://github.com/user-attachments/assets/143c98d5-636d-4244-9a31-84780bd14eed)
(注：上图中的三个so文件是从正常生效的ubuntu机器的tugraph container中copy过来的)
尝试2: 把涉及的so文件copy到container对应路径下也未生效，仍会尝试加载cpp

**Comment by evilbear** [comment]
以trick的方式临时解决了我的问题，先替换插件和db相关的文件夹再restart。但还是期望能修复相关问题

1. 前提条件，我在ubuntu上有一个work的版本，在tugraph的container中取出plugin和mdb相关的信息，用到了两个文件夹
1.1 在/var/lib/lgraph/data路径下有一个类似FE32344205C15BBEC329C8928CF4E217的文件夹
1.2 还有一个/var/lib/lgraph/data/.meta 文件夹 (里面是data.mdb和lock.mdb)
2. 在centos9中，将1.1对应的文件夹复制到tugraph的container里对应的路径下；  将1.2文件夹里的内容替换这里对应路径下的内容
3. docker restart container之后tugraph已经有了插件，后续流程work

在tugraph的/var/log/lgraph_log路径下有一些报错的日志信息供参考
general.log:
[2024-Jul-17 01:45:40.787796] [INFO] -
**********************************************************************
*                  TuGraph Graph Database v4.0.1                     *
*                                                                    *
*    Copyright(C) 2018-2023 Ant Group. All rights reserved.          *
*                                                                    *
**********************************************************************
Server is configured with the following parameters:
  Backup log enable:               0
  DB directory:                    /var/lib/lgraph/data
  HA enable:                       0
  HTTP port:                       7070
  HTTP web dir:                    /usr/local/share/lgraph/resource
  RPC enable:                      1
  RPC port:                        9090
  SSL enable:                      0
  Whether the token is unlimited:  0
  audit log enable:                0
  bind host:                       0.0.0.0
  disable auth:                    0
  durable:                         0
  log dir:                         /var/log/lgraph_log
  log verbose:                     1
  optimistic transaction:          0
  subprocess idle limit:           600
  thread limit:                    0
[2024-Jul-17 01:45:40.834177] [INFO] - [StateMachine] Builtin services are disabled according to ServerOptions.has_builtin_services
[2024-Jul-17 01:45:40.834780] [INFO] - Listening for RPC on port 9090
[2024-Jul-17 01:45:40.834927] [DEBUG] [Galaxy] - Loading DB state from disk
[2024-Jul-17 01:45:40.836529] [DEBUG] - Killing all python processes
[2024-Jul-17 01:45:40.838747] [INFO] [RestServer] - Listening for REST on port 7070
[2024-Jul-17 01:45:40.838789] [INFO] - Server started.
[2024-Jul-17 06:26:52.698465] [INFO] -
**********************************************************************
Server is configured with the following parameters:
  Backup log enable:               0
  DB directory:                    /var/lib/lgraph/data
  HA enable:                       0
  HTTP port:                       7070
  HTTP web dir:                    /usr/local/share/lgraph/resource
  RPC enable:                      1
  RPC port:                        9090
  SSL enable:                      0
  Whether the token is unlimited:  0
  audit log enable:                0
  bind host:                       0.0.0.0
  disable auth:                    0
  durable:                         0
  log dir:                         /var/log/lgraph_log
  log verbose:                     1
  optimistic transaction:          0
  subprocess idle limit:           600
  thread limit:                    0
[2024-Jul-17 06:26:52.738449] [INFO] - [StateMachine] Fail to listen 0.0.0.0:9090
[2024-Jul-17 06:26:52.738510] [WARNING] - RPC server returns -1, try again after 1s
[2024-Jul-17 06:26:53.738663] [INFO] - [StateMachine] Fail to listen 0.0.0.0:9090
[2024-Jul-17 06:26:53.738731] [WARNING] - RPC server returns -1, try again after 1s
[2024-Jul-17 06:26:54.738879] [INFO] - [StateMachine] Fail to listen 0.0.0.0:9090
[2024-Jul-17 06:26:54.738971] [WARNING] - RPC server returns -1, try again after 1s
[2024-Jul-17 06:26:55.739087] [INFO] - [StateMachine] Fail to listen 0.0.0.0:9090
[2024-Jul-17 06:26:55.739156] [WARNING] - RPC server returns -1, try again after 1s
[2024-Jul-17 06:26:56.739360] [INFO] - [StateMachine] Fail to listen 0.0.0.0:9090
[2024-Jul-17 06:26:56.739431] [WARNING] - RPC server returns -1, try again after 1s
[2024-Jul-17 06:26:57.739568] [ERROR] - Failed to start RPC server
[2024-Jul-17 06:27:50.895821] [INFO] - !!!!! Received signal 2, exiting... !!!!!
[2024-Jul-17 06:27:50.895920] [INFO] - Stopping TuGraph...
[2024-Jul-17 06:27:50.896214] [INFO] - Server shutdown.

debug.log:
[2024-Jul-17 06:19:08.231983] [INFO] [RestServer] - Illegal request: POST /db/default/cpp_plugin HTTP/1.1^M
Accept: application/json, text/plain, */*^M
Accept-Encoding: gzip, deflate^M
Accept-Language: zh,zh-TW;q=0.9,en-US;q=0.8,en;q=0.7^M
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9sb2dpbl90aW1lIjoiMTcyMTE4MjE5NS4wNTgzNDAiLCJpc3MiOiJmbWEuYWkiLCJyZWZyZXNoX3RpbWUiOiIxNzIxMTk0MzEyLjEwMDU1NiJ9.gVePBpB8ewyIy_qOXmNTq6sQKmXvXIR77ry2FXcHrpA^M
Connection: keep-alive^M
Content-Length: 6857^M
Content-Type: application/json^M
Cookie: _streamlit_xsrf=2|950b8ada|f8061135116b861ec67ce7c1c3c47e44|1720084985; x-hng=lang=zh-CN; ctoken=bigfish_ctoken_1980edj0jc^M
Host: 172.18.133.27:7070^M
Origin: http://172.18.133.27:7070^M
Referer: http://172.18.133.27:7070/^M
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36^M
^M

[2024-Jul-17 06:19:08.232082] [INFO] [RestServer] - RespondBadRequest error info : Timeout while compiling plugin.
Stdout:----

Stderr:----
