### ISSUE TITLE
openspg 前端无法访问

### ISSUE THREAD

**Issue by Nicole00** [OpenSPG/openspg#329]
源码启动的openspg-server，按照[文档](https://openspg.yuque.com/ndx6g9/nmwkzz/egceglvxrcfgovny) 执行 知识加工时失败。

执行` knext builder execute Company`失败：

```
2024-07-26 11:42:16,436 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.lang.RuntimeException: Failed to find PemJa Library
	at pemja.utils.CommonUtils.getLibraryPathWithPattern(CommonUtils.java:119)
	at pemja.core.PythonInterpreter$MainInterpreter.initialize(PythonInterpreter.java:356)
	at pemja.core.PythonInterpreter.initialize(PythonInterpreter.java:145)
	at pemja.core.PythonInterpreter.<init>(PythonInterpreter.java:46)
	at com.antgroup.openspg.builder.core.physical.operator.PythonOperatorFactory.newPythonInterpreter(PythonOperatorFactory.java:55)
	at com.antgroup.openspg.builder.core.physical.operator.PythonOperatorFactory.init(PythonOperatorFactory.java:63)
	at com.antgroup.openspg.builder.core.physical.process.BaseExtractProcessor.doInit(BaseExtractProcessor.java:48)
	at com.antgroup.openspg.builder.core.physical.BasePhysicalNode.init(BasePhysicalNode.java:71)
	at com.antgroup.openspg.builder.core.runtime.impl.DefaultBuilderExecutor.init(DefaultBuilderExecutor.java:37)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderRunner.init(LocalBuilderRunner.java:80)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:147)
	at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)
```

**Comment by andylau-55** [comment]
目前openspg前端代码暂未开源，如果需要使用可视化页面可拉取docker镜像进行部署，参考文档：https://openspg.yuque.com/ndx6g9/nmwkzz/xht6kkegvs33cwwr
