### ISSUE TITLE
knext builder报错

### ISSUE THREAD

**Issue by XenaLiu** [OpenSPG/openspg#338]
(openspg_venv) root@docker-desktop:/code/python/knext/knext/examples/supplychain# knext builder execute TaxOfCompanyEvent
2024-08-19 08:28:44,506 [] [] [main] ERROR c.a.o.b.r.l.LocalBuilderMain - unknown exception.
java.lang.ClassCastException: java.lang.String cannot be cast to com.antgroup.openspg.core.schema.model.type.ProjectSchema
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.getProjectSchema(LocalBuilderMain.java:164)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.run(LocalBuilderMain.java:132)
        at com.antgroup.openspg.builder.runner.local.LocalBuilderMain.main(LocalBuilderMain.java:69)

**Comment by andylau-55** [comment]
Server and Python version mismatch. Please provide your local environment configuration, openspg-server and openspg-python. Installation Instructions : https://openspg.yuque.com/ndx6g9/nmwkzz/xht6kkegvs33cwwr

**Comment by XenaLiu** [comment]
I'm using the latest Docker image, released August 19

**Comment by andylau-55** [comment]
Whether openspg-server is started from source or docker? Please provide the docker version information

**Comment by andylau-55** [comment]
Thanks for your feedback. Due to the docker network problem, the previous image cannot be obtained. Please follow the  document to fetch the latest openspg-python image again
https://openspg.yuque.com/ndx6g9/nmwkzz/xht6kkegvs33cwwr
