### ISSUE TITLE
问答的时候ERROR

### ISSUE THREAD

**Issue by MachineWei** [OpenSPG/openspg#392]
执行失败pemja.core.PythonException: <class 'AttributeError'>: 'NoneType' object has no attribute 'get'
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/main_solver.invoke(main_solver.py:31)
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/implementation/default_lf_planner.__init__(default_lf_planner.py:20)
	at /openspg_venv/lib/python3.8/site-packages/kag/interface/solver/lf_planner_abc.__init__(lf_planner_abc.py:15)
	at /openspg_venv/lib/python3.8/site-packages/kag/solver/common/base.__init__(base.py:114)
	at pemja.core.PythonInterpreter.invokeMethod(Native Method)
	at pemja.core.PythonInterpreter.invokeMethod(PythonInterpreter.java:118)
	at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:143)
	at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:122)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

docker日志：
```text
2024-11-06 11:21:16,228 [] [] [http-nio-8887-exec-20] INFO  c.a.o.c.r.s.i.TaskServiceImpl - start_run_nlQuery_task,task={"dsl":"利息是指什么","id":6,"nl":"利息是指什么","params":{},"projectId":1,"resultMessage":"[]","sessionId":2,"status":"INIT","userId":111111}
2024-11-06 11:21:16,254 [] [] [pool-1-thread-3] ERROR c.a.o.c.r.s.i.TaskRunner - nl query execute error,
pemja.core.PythonException: <class 'AttributeError'>: 'NoneType' object has no attribute 'get'
        at /openspg_venv/lib/python3.8/site-packages/kag/solver/main_solver.invoke(main_solver.py:31)
        at /openspg_venv/lib/python3.8/site-packages/kag/solver/implementation/default_lf_planner.__init__(default_lf_planner.py:20)
        at /openspg_venv/lib/python3.8/site-packages/kag/interface/solver/lf_planner_abc.__init__(lf_planner_abc.py:15)
        at /openspg_venv/lib/python3.8/site-packages/kag/solver/common/base.__init__(base.py:114)
        at pemja.core.PythonInterpreter.invokeMethod(Native Method)
        at pemja.core.PythonInterpreter.invokeMethod(PythonInterpreter.java:118)
        at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:143)
        at com.antgroup.openspgapp.core.reasoner.service.impl.TaskRunner$NlQueryTask.call(TaskRunner.java:122)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2024-11-06 11:21:17,007 [] [] [Thread-3] INFO  c.a.o.c.r.s.i.TaskRunner - reasoner_task_done,id=6
2024-11-06 11:21:17,008 [] [] [Thread-3] INFO  c.a.o.c.r.s.i.TaskCallBack - reasoner_task_id=6,update_status=ERROR
```

这是什么原因？
neo4j、mysql都正常写入。

**Comment by DearAS** [comment]
怎么解决的
