### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by ProphetMo** [OpenSPG/openspg#395]
项目启动初始化的时候 报出了如图下的错误，大概是对象ReasonController实例下一系列依赖注入的问题，追溯到了ReasonServiceImpl实例对象。爆出了NoClassDefFoundError，不弄初始化com.antgroup.openspg.reasoner.common.types.KTLong$ KTObject$ KTString$这两个类，。
![image](https://github.com/user-attachments/assets/3a8e2e29-f5a0-4064-b28c-538a7019cbe8)
com.antgroup.openspg.reasoner.common.types文件目录如下
![image](https://github.com/user-attachments/assets/1ae614bb-14c1-4541-b99d-435b95d88aa9)

所有运行日志文件如下
`
2024-11-07 17:03:42.009  INFO 11416 --- [           main] com.alipay.sofa                          : SOFABoot Runtime Starting!
2024-11-07 17:03:42,022 [] [] [main] INFO  c.a.o.s.a.s.Application - Starting Application using Java 1.8.0_271 on DESKTOP-INFA2S8 with PID 11416 (E:\IDEA_workshop\IdeaProjects\openspg\server\arks\sofaboot\target\classes started by 37484 in E:\IDEA_workshop\IdeaProjects\openspg)
2024-11-07 17:03:42,022 [] [] [main] INFO  c.a.o.s.a.s.Application - No active profile set, falling back to 1 default profile: "default"
2024-11-07 17:03:44,725 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.autoconfigure.tracer.TracerAnnotationAutoConfiguration' of type [com.alipay.sofa.boot.autoconfigure.tracer.TracerAnnotationAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,738 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.tracer.zipkin-com.alipay.sofa.tracer.boot.zipkin.properties.ZipkinSofaTracerProperties' of type [com.alipay.sofa.tracer.boot.zipkin.properties.ZipkinSofaTracerProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,739 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.autoconfigure.tracer.ZipkinSofaTracerAutoConfiguration' of type [com.alipay.sofa.boot.autoconfigure.tracer.ZipkinSofaTracerAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,739 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'zipkinSofaTracerRestTemplateCustomizer' of type [com.alipay.sofa.tracer.plugins.zipkin.ZipkinSofaTracerRestTemplateCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,773 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'zipkinSofaTracerSpanReporter' of type [com.alipay.sofa.tracer.plugins.zipkin.ZipkinSofaTracerSpanRemoteReporter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,774 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.autoconfigure.tracer.SofaTracerAutoConfiguration' of type [com.alipay.sofa.boot.autoconfigure.tracer.SofaTracerAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,777 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.tracer-com.alipay.sofa.tracer.boot.properties.SofaTracerProperties' of type [com.alipay.sofa.tracer.boot.properties.SofaTracerProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,800 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sofaTracer' of type [com.alipay.sofa.tracer.plugin.flexible.FlexibleTracer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,803 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sofaMethodInvocationProcessor' of type [com.alipay.sofa.tracer.boot.flexible.processor.SofaTracerMethodInvocationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,803 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sofaTracerIntroductionInterceptor' of type [com.alipay.sofa.tracer.boot.flexible.processor.SofaTracerIntroductionInterceptor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,943 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.autoconfigure.startup.SofaStartupAutoConfiguration' of type [com.alipay.sofa.boot.autoconfigure.startup.SofaStartupAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,949 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.startup-com.alipay.sofa.startup.StartupProperties' of type [com.alipay.sofa.startup.StartupProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,950 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'com.alipay.sofa.boot.autoconfigure.tracer.SofaTracerRestTemplateAutoConfiguration' of type [com.alipay.sofa.boot.autoconfigure.tracer.SofaTracerRestTemplateAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:44,955 [] [] [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sofaTracerRestTemplateEnhance' of type [com.alipay.sofa.tracer.boot.resttemplate.SofaTracerRestTemplateEnhance] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-11-07 17:03:45,409 [] [] [main] INFO  o.s.b.w.e.t.TomcatWebServer - Tomcat initialized with port(s): 8887 (http)
2024-11-07 17:03:45,409 [] [] [main] INFO  o.a.c.c.AprLifecycleListener - An older version [1.2.24] of the Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.30]
2024-11-07 17:03:45,409 [] [] [main] INFO  o.a.c.c.AprLifecycleListener - Loaded Apache Tomcat Native library [1.2.24] using APR version [1.7.0].
2024-11-07 17:03:45,409 [] [] [main] INFO  o.a.c.c.AprLifecycleListener - APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [false].
2024-11-07 17:03:45,410 [] [] [main] INFO  o.a.c.c.AprLifecycleListener - APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2024-11-07 17:03:45,413 [] [] [main] INFO  o.a.c.c.AprLifecycleListener - OpenSSL successfully initialized [OpenSSL 1.1.1g  21 Apr 2020]
2024-11-07 17:03:45,431 [] [] [main] INFO  o.a.c.h.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8887"]
2024-11-07 17:03:45,431 [] [] [main] INFO  o.a.c.c.StandardService - Starting service [Tomcat]
2024-11-07 17:03:45,431 [] [] [main] INFO  o.a.c.c.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.71]
2024-11-07 17:03:45,715 [] [] [main] INFO  o.a.c.c.C.[.[.[/] - Initializing Spring embedded WebApplicationContext
2024-11-07 17:03:45,715 [] [] [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 3598 ms
2024-11-07 17:03:47,052 [] [] [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reasonController': Unsatisfied dependency expressed through field 'reasonerManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reasonerManagerImpl': Unsatisfied dependency expressed through field 'reasonerService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reasonerServiceImpl': Invocation of init method failed; nested exception is io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTLong$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTObject$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTString$, java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
2024-11-07 17:03:48,068 [] [] [main] WARN  z.r.AsyncReporter$BoundedAsyncReporter - Timed out waiting for in-flight spans to send
2024-11-07 17:03:48,075 [] [] [main] INFO  o.a.c.c.StandardService - Stopping service [Tomcat]
2024-11-07 17:03:48,081 [] [] [main] WARN  o.a.c.l.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:41)
2024-11-07 17:03:48,096 [] [] [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-11-07 17:03:48,150 [] [] [main] ERROR o.s.b.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reasonController': Unsatisfied dependency expressed through field 'reasonerManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reasonerManagerImpl': Unsatisfied dependency expressed through field 'reasonerService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reasonerServiceImpl': Invocation of init method failed; nested exception is io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTLong$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTObject$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTString$, java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.antgroup.openspg.server.arks.sofaboot.Application.main(Application.java:39)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reasonerManagerImpl': Unsatisfied dependency expressed through field 'reasonerService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reasonerServiceImpl': Invocation of init method failed; nested exception is io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTLong$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTObject$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTString$, java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reasonerServiceImpl': Invocation of init method failed; nested exception is io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTLong$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTObject$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTString$, java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 34 common frames omitted
Caused by: io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTLong$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTObject$, java.lang.NoClassDefFoundError: Could not initialize class com.antgroup.openspg.reasoner.common.types.KTString$, java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
	at io.github.lukehutch.fastclasspathscanner.MatchProcessorException.newInstance(MatchProcessorException.java:82)
	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:583)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1411)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1472)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1495)
	at com.antgroup.openspg.reasoner.udf.impl.UdfMngImpl.getUdfInPath(UdfMngImpl.java:198)
	at com.antgroup.openspg.reasoner.udf.impl.UdfMngImpl.createInstance(UdfMngImpl.java:125)
	at com.antgroup.openspg.reasoner.udf.impl.UdfMngImpl.getInstance(UdfMngImpl.java:103)
	at com.antgroup.openspg.server.core.reasoner.service.impl.ReasonerServiceImpl.init(ReasonerServiceImpl.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 46 common frames omitted

Process finished with exit code 1`

**Comment by caszkgui** [comment]
you can refer to [user manual ](https://openspg.yuque.com/ndx6g9/0.5/xfsvolpck828hlfr) to build openspg locally.
your errorlog looks like openspg.reasoner has not been compiled successfully.

**Comment by ProphetMo** [comment]
我按照[user manual](https://openspg.yuque.com/ndx6g9/0.5/xfsvolpck828hlfr)的步骤 
执行mvn编译命令mvn clean install -Dmaven.test.skip=true -Dspotless.check.skip -Dspotless.apply.skip
编译到reasoner-common就出错了
![image](https://github.com/user-attachments/assets/4f0bd486-a7de-4275-b8d4-43126b0b8f71)

**Comment by andylau-55** [comment]
Are all the dependencies installed?
![image](https://github.com/user-attachments/assets/0173379e-1541-483d-b770-fc6759a628de)

**Comment by ProphetMo** [comment]
我的问题解决了，这个源码部署是没有可视化界面的吗

**Comment by andylau-55** [comment]
> 我的问题解决了，这个源码部署是没有可视化界面的吗

The front-end code is not open source at the moment
