### ISSUE TITLE
使用docker compse方式部署openspg，server容器启动报错（Unknown database ‘openspg’）

### ISSUE THREAD

**Issue by qzbqzb** [OpenSPG/openspg#441]
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - sun.java.launcher=SUN_STANDARD
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - sun.jnu.encoding=UTF-8
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - sun.management.compiler=HotSpot 64-Bit Tiered Compilers
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - sun.os.patch.level=unknown
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - user.dir=/
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - user.home=/root
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - user.language=en
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - user.name=root
2024-12-28 15:55:11,644 [] [] [main] INFO  c.a.o.s.a.s.EnvironmentPropertiesPrinter - user.timezone=Asia/Shanghai
2024-12-28 15:55:11,648 [] [] [main] INFO  c.a.o.a.s.Application - Started Application in 12.65 seconds (JVM running for 13.46)
2024-12-28 15:55:11,744 [] [] [main] INFO  c.a.o.a.s.Application - OpenSPG Application Started!!!
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application -   ___                   ____  ____   ____
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application -  / _ \ _ __   ___ _ __ / ___||  _ \ / ___|
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application - | | | | '_ \ / _ \ '_ \\___ \| |_) | |  _
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application - | |_| | |_) |  __/ | | |___) |  __/| |_| |
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application -  \___/| .__/ \___|_| |_|____/|_|    \____|
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application -       |_|
2024-12-28 15:55:11,745 [] [] [main] INFO  c.a.o.a.s.Application - * Running on http://127.0.0.1:8887
2024-12-28 15:55:11,746 [] [] [main] INFO  c.a.o.a.s.Application - * Running on http://172.21.0.4:8887
2024-12-28 15:55:12,065 [] [] [pool-2-thread-1] ERROR c.a.o.s.c.s.l.i.RdbDistributeLockServiceImpl - clean time out lock fail
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'openspg'
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy94.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
        at com.sun.proxy.$Proxy113.selectByExample(Unknown Source)
        at com.antgroup.openspg.server.infra.dao.repository.common.SysLockRepositoryImpl.queryAllLock(SysLockRepositoryImpl.java:38)
        at com.antgroup.openspg.server.infra.dao.repository.common.SysLockRepositoryImpl$$FastClassBySpringCGLIB$$cd96e635.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.antgroup.openspg.server.infra.dao.repository.common.SysLockRepositoryImpl$$EnhancerBySpringCGLIB$$f22c797f.queryAllLock(<generated>)
        at com.antgroup.openspg.server.common.service.lock.impl.RdbDistributeLockServiceImpl.removeTimeOutLock(RdbDistributeLockServiceImpl.java:73)
        at com.antgroup.openspg.server.common.service.lock.impl.RdbDistributeLockServiceImpl.lambda$init$0(RdbDistributeLockServiceImpl.java:48)

**Comment by qzbqzb** [comment]
已解决，定位原因是mysql容器缺少/var/lib/mysql路径的权限，导致创建openspg数据库失败

**Comment by lzh00** [comment]
你好，我也遇到了类似的问题。如下：
2025-02-12 12:25:51,154 [] [] [pool-2-thread-1] ERROR c.a.o.s.c.s.l.i.RdbDistributeLockServiceImpl - clean time out lock fail
^Corg.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
### The error may exist in class path resource [mapper/SysLockDOMapper.xml]
### The error may involve com.antgroup.openspg.server.infra.dao.mapper.SysLockDOMapper.selectByExample
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure


在/var/lib/目录下，没有找到mysql，创建了一个，并修改755权限，还是同样的error。请问您具体是怎么解决的？提前感谢~
